language: ruby
rvm:
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-9.1.8.0
script: 
  rake rspec_wrapped SETTINGS='ci'
cache:
  directories:
  - solrmarc-sw
notifications:
  email:
    - ndushay@stanford.edu
    - laneymcg@stanford.edu
