# settings for production
prod:
  solrmarc_dist_dir: your_production_solrmarc_dist_dir
  solrmarc_conf_props_file: your_solrmarc_config.properties
  solr_url: your_production_solr_url
  log_level: error

# settings for local development
dev:
  solrmarc_dist_dir: your_solrmarc_dist_dir
  solrmarc_conf_props_file: your_solrmarc_config.properties
  solr_url: http://127.0.0.1:8983/solr/dev
  log_level: info

# settings for continuous integration
ci:
  solrmarc_dist_dir: solrmarc/dist
  solrmarc_conf_props_file: solrmarc/dist/sw_config.properties
  solr_url: http://127.0.0.1:8983/solr/test
  log_level: info
    
# add:
#solr id field?
#solr marcxml field?
